name: "Pensar scan"
description: "Scan for and automatically fix security vulnerabilities in your codebase."
inputs:
  local:
    description: "Run Pensar fully locally using opensource models. This will require a larger action runner to use."
    required: false
    default: "false"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.local }}